### ISSUE TITLE
Process task again when it's _state changes from finished_state to start_state

### ISSUE THREAD

**Issue by rafalsobota** [firebase/firebase-queue#41] opened 2016-01-18 14:35 UTC
When I manually change task's _state from random value to start_state it is picked up by worker properly. But when I change _state from worker's finished_state to start_state it's not. Is it on purpose?

**Comment by drtriumph** [comment] 2016-01-24 04:10
This isn't intended behavior, what version of node / firebase / firebase-queue are you running?

**Comment by rafalsobota** [comment] 2016-01-24 11:27
node 5.4.0
firebase 2.3.2
firebase-queue 1.2.1

**Comment by drtriumph** [comment] 2016-01-29 18:15
We deployed a fix to the realtime database yesterday for something that might have been causing the issue you see here. Let me know if it still doesn't work as expected and we'll dig in further

**Comment by chevsky** [comment] 2016-02-04 18:04
+1

**Comment by drtriumph** [comment] 2016-02-11 00:03
Closing this out - we deployed a new fix for the database on Friday last week that was likely the cause of this. If you're still having issues, please reopen with an [mvce](http://stackoverflow.com/help/mcve).

**Closed by drtriumph** 2016-02-11 00:03 UTC
